Krypton:
  - '@ater1'
  - '@braden-m'
  - '@caitlinmwillington'
  - '@chy-m'
  - '@dan-lennox'
  - '@jchillemi'
  - '@paulofla'
  - '@Xuester'
Mercury:
  - '@dNitza'
  - '@Gwash3189'
  - '@markreid'
  - '@RohanSharma4'
  - '@zoe0119'
  - '@Moskvyak'
  - '@felixsebastian'
  - '@mike-kent-ca'
  - '@dscultureamp'
Sol:
  - '@juliohr'
  - '@dabarrell'
  - '@m-dwyer'
  - '@princeprescott'
  - '@deepsainath'
Earthlings:
  - '@AndrewMcCraeCA'
  - '@quangkhoa'
  - '@sumandeep0808'
  - '@Confidenceman02'
  - '@fugu-chop'
  - '@dalebaldwin'
  - '@talbet'

